#!/bin/bash

if [ -z "$1" ]; then
    echo "input-file can't be empty!"
    exit
fi

if [ ! -f $1 ]; then
    echo "input-file '$1' not found!"
    exit
fi

for i in {11..14}
do
    echo "scp $1 farmer@192.168.17.$i:$2"
    scp $1 farmer@192.168.17.$i:$2
done

